# Generated by Django 6.0.3 on 2026-07-23 03:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('PROFILE_APPROVED', 'Hồ sơ đã phê duyệt'), ('NEW_PUBLICATIONS_DETECTED', 'Phát hiện bài báo mới'), ('METRICS_UPDATED', 'Cập nhật chỉ số trích dẫn'), ('SYSTEM_NOTICE', 'Thông báo hệ thống')], db_index=True, default='SYSTEM_NOTICE', max_length=50, verbose_name='Notification Type')),
                ('category', models.CharField(choices=[('PERSONAL', 'Cá nhân'), ('SCHOLAR', 'Bài báo & Đề tài'), ('SYSTEM', 'Hệ thống')], db_index=True, default='SCHOLAR', max_length=30, verbose_name='Category')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra contextual data e.g. new_count, total_pubs, scholar_id', verbose_name='Metadata')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Target Link')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Is Read')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'user_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
