# Generated by Django 6.0.3 on 2026-07-17 03:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scholar_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Scholar ID')),
                ('name', models.CharField(max_length=250, verbose_name='Full Name')),
                ('affiliation', models.CharField(blank=True, max_length=500, null=True, verbose_name='Affiliation')),
                ('citedby', models.IntegerField(default=0, verbose_name='Total Citations')),
                ('hindex', models.IntegerField(default=0, verbose_name='H-Index')),
                ('i10index', models.IntegerField(default=0, verbose_name='i10-Index')),
                ('interests', models.JSONField(blank=True, default=list, verbose_name='Interests')),
            ],
            options={
                'verbose_name': 'Author Profile',
                'verbose_name_plural': 'Author Profiles',
                'db_table': 'scholar_authors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clarivate_title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Clarivate Title')),
                ('title_normalized', models.CharField(db_index=True, max_length=500, verbose_name='Normalized Title')),
                ('issn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ISSN')),
                ('eissn', models.CharField(blank=True, max_length=20, null=True, verbose_name='eISSN')),
                ('publisher', models.CharField(blank=True, max_length=500, null=True, verbose_name='Publisher')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('wos_core_collection', models.CharField(blank=True, max_length=250, null=True, verbose_name='WoS Core Collection')),
                ('additional_wos_indexes', models.CharField(blank=True, max_length=250, null=True, verbose_name='Additional WoS Indexes')),
                ('latest_if', models.FloatField(blank=True, null=True, verbose_name='Latest Impact Factor')),
                ('latest_if_year', models.IntegerField(blank=True, null=True, verbose_name='Latest IF Year')),
                ('latest_sjr', models.FloatField(blank=True, null=True, verbose_name='Latest SJR Score')),
                ('latest_sjr_year', models.IntegerField(blank=True, null=True, verbose_name='Latest SJR Year')),
                ('latest_quartile', models.CharField(blank=True, max_length=10, null=True, verbose_name='Latest Quartile')),
                ('latest_h_index', models.IntegerField(blank=True, null=True, verbose_name='Latest H-Index')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
                'db_table': 'scholar_journals',
                'ordering': ['clarivate_title', 'title_normalized'],
            },
        ),
        migrations.CreateModel(
            name='JournalISSN',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issn', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='ISSN')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issns', to='scholar.journal', verbose_name='Journal')),
            ],
            options={
                'verbose_name': 'Journal ISSN',
                'verbose_name_plural': 'Journal ISSNs',
                'db_table': 'scholar_journal_issns',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(verbose_name='Title')),
                ('authors_list', models.TextField(blank=True, null=True, verbose_name='Authors List')),
                ('venue', models.TextField(blank=True, null=True, verbose_name='Venue/Journal')),
                ('year', models.CharField(blank=True, max_length=50, null=True, verbose_name='Year')),
                ('citations', models.IntegerField(default=0, verbose_name='Citations Count')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('cites_per_year', models.JSONField(blank=True, default=dict, verbose_name='Citations Per Year History')),
                ('sjr_q', models.CharField(default='N/A', max_length=10, verbose_name='Matched SJR Quartile')),
                ('if_val', models.CharField(default='N/A', max_length=20, verbose_name='Matched Impact Factor')),
                ('wos', models.CharField(default='N/A', max_length=150, verbose_name='Matched Web of Science')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='scholar.authorprofile', verbose_name='Author')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='scholar.journal', verbose_name='Matched Journal')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'db_table': 'scholar_publications',
                'ordering': ['display_order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='JournalRanking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(verbose_name='Year')),
                ('impact_factor', models.FloatField(blank=True, null=True, verbose_name='Impact Factor')),
                ('sjr_score', models.FloatField(blank=True, null=True, verbose_name='SJR Score')),
                ('sjr_quartile', models.CharField(blank=True, max_length=10, null=True, verbose_name='SJR Quartile')),
                ('h_index', models.IntegerField(blank=True, null=True, verbose_name='Journal H-Index')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='scholar.journal', verbose_name='Journal')),
            ],
            options={
                'verbose_name': 'Journal Ranking',
                'verbose_name_plural': 'Journal Rankings',
                'db_table': 'scholar_journal_rankings',
                'ordering': ['-year'],
                'unique_together': {('journal', 'year')},
            },
        ),
    ]
