# Generated by Django 6.0.3 on 2026-07-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='additional_wos_indexes',
            field=models.TextField(blank=True, null=True, verbose_name='Additional WoS Indexes'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='clarivate_title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Clarivate Title'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='country',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='eissn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='eISSN'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='issn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ISSN'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='publisher',
            field=models.TextField(blank=True, null=True, verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='title_normalized',
            field=models.CharField(db_index=True, max_length=1000, verbose_name='Normalized Title'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='wos_core_collection',
            field=models.TextField(blank=True, null=True, verbose_name='WoS Core Collection'),
        ),
    ]
