# Generated by Django 6.0.3 on 2026-07-17 04:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0002_alter_journal_additional_wos_indexes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioxbioCrawlerProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=250, unique=True, verbose_name='Subject Category')),
                ('last_completed_page', models.IntegerField(default=0, verbose_name='Last Completed Page')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
            ],
            options={
                'db_table': 'scholar_raw_bioxbio_progress',
            },
        ),
        migrations.CreateModel(
            name='BioxbioJournal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=1000, verbose_name='BioxBio Title')),
                ('title_normalized', models.CharField(db_index=True, max_length=1000, unique=True, verbose_name='Normalized Title')),
            ],
            options={
                'db_table': 'scholar_raw_bioxbio_journals',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ClarivateCrawlerProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.IntegerField(unique=True, verbose_name='Page Number')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
            ],
            options={
                'db_table': 'scholar_raw_clarivate_progress',
            },
        ),
        migrations.CreateModel(
            name='ClarivateJournal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publication_id', models.IntegerField(unique=True, verbose_name='Publication ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Clarivate Title')),
                ('title_normalized', models.CharField(db_index=True, max_length=1000, verbose_name='Normalized Title')),
                ('issn', models.CharField(blank=True, max_length=50, null=True, verbose_name='ISSN')),
                ('eissn', models.CharField(blank=True, max_length=50, null=True, verbose_name='eISSN')),
                ('publisher', models.TextField(blank=True, null=True, verbose_name='Publisher')),
                ('country', models.CharField(blank=True, max_length=250, null=True, verbose_name='Country')),
                ('wos_core_collection', models.TextField(blank=True, null=True, verbose_name='WoS Core Collection')),
                ('additional_wos_indexes', models.TextField(blank=True, null=True, verbose_name='Additional WoS Indexes')),
            ],
            options={
                'db_table': 'scholar_raw_clarivate_journals',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ScimagoJournal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_id', models.IntegerField(unique=True, verbose_name='Source ID')),
                ('title', models.CharField(max_length=1000, verbose_name='SCImago Title')),
                ('title_normalized', models.CharField(db_index=True, max_length=1000, verbose_name='Normalized Title')),
                ('journal_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Journal Type')),
                ('publisher', models.TextField(blank=True, null=True, verbose_name='Publisher')),
                ('country', models.CharField(blank=True, max_length=250, null=True, verbose_name='Country')),
            ],
            options={
                'db_table': 'scholar_raw_scimago_journals',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='journal',
            name='bioxbio_match',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='BioxBio Match Method'),
        ),
        migrations.AddField(
            model_name='journal',
            name='scimago_match',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SCImago Match Method'),
        ),
        migrations.AlterField(
            model_name='journalissn',
            name='issn',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='ISSN'),
        ),
        migrations.CreateModel(
            name='BioxbioISSN',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issn', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='ISSN')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_issns', to='scholar.bioxbiojournal')),
            ],
            options={
                'db_table': 'scholar_raw_bioxbio_issns',
            },
        ),
        migrations.AddField(
            model_name='journal',
            name='bioxbio_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapped_journals', to='scholar.bioxbiojournal'),
        ),
        migrations.CreateModel(
            name='ScimagoISSN',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issn', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='ISSN')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_issns', to='scholar.scimagojournal')),
            ],
            options={
                'db_table': 'scholar_raw_scimago_issns',
            },
        ),
        migrations.AddField(
            model_name='journal',
            name='scimago_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapped_journals', to='scholar.scimagojournal'),
        ),
        migrations.CreateModel(
            name='BioxbioRanking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(verbose_name='Year')),
                ('impact_factor', models.FloatField(blank=True, null=True, verbose_name='Impact Factor')),
                ('total_articles', models.IntegerField(blank=True, null=True, verbose_name='Total Articles')),
                ('total_cites', models.IntegerField(blank=True, null=True, verbose_name='Total Citations')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_rankings', to='scholar.bioxbiojournal')),
            ],
            options={
                'db_table': 'scholar_raw_bioxbio_rankings',
                'ordering': ['-year'],
                'unique_together': {('journal', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ScimagoRanking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(verbose_name='Year')),
                ('sjr_score', models.FloatField(blank=True, null=True, verbose_name='SJR Score')),
                ('sjr_quartile', models.CharField(blank=True, max_length=10, null=True, verbose_name='SJR Quartile')),
                ('h_index', models.IntegerField(blank=True, null=True, verbose_name='H-Index')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_rankings', to='scholar.scimagojournal')),
            ],
            options={
                'db_table': 'scholar_raw_scimago_rankings',
                'ordering': ['-year'],
                'unique_together': {('journal', 'year')},
            },
        ),
    ]
