# Generated by Django 6.0.3 on 2026-07-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0003_bioxbiocrawlerprogress_bioxbiojournal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioxbiojournal',
            name='source_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Source ID'),
        ),
    ]
