# Generated by Django 6.0.3 on 2026-07-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0004_bioxbiojournal_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scimagojournal',
            name='source_id',
            field=models.BigIntegerField(unique=True, verbose_name='Source ID'),
        ),
    ]
