# Generated by Django 6.0.3 on 2026-07-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0005_alter_scimagojournal_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='is_staging',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Staging'),
        ),
    ]
