# Generated by Django 6.0.3 on 2026-07-20 02:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0006_journal_is_staging'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.CharField(max_length=255, unique=True, verbose_name='Celery Task ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('status', models.CharField(default='PENDING', max_length=50, verbose_name='Status')),
                ('is_automated', models.BooleanField(default=False, verbose_name='Is Automated')),
                ('clarivate_count', models.IntegerField(default=0, verbose_name='Clarivate Scraped')),
                ('scimago_count', models.IntegerField(default=0, verbose_name='SCImago Scraped')),
                ('bioxbio_count', models.IntegerField(default=0, verbose_name='BioxBio Scraped')),
                ('mapped_count', models.IntegerField(default=0, verbose_name='Mapped Journals')),
                ('log_output', models.TextField(blank=True, default='', verbose_name='Console Log Output')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
            ],
            options={
                'verbose_name': 'Crawl History',
                'verbose_name_plural': 'Crawl Histories',
                'db_table': 'scholar_crawl_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
