# Generated by Django 6.0.3 on 2026-07-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0007_crawlhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlhistory',
            name='bioxbio_total',
            field=models.IntegerField(default=0, verbose_name='BioxBio Total'),
        ),
        migrations.AddField(
            model_name='crawlhistory',
            name='clarivate_total',
            field=models.IntegerField(default=0, verbose_name='Clarivate Total'),
        ),
        migrations.AddField(
            model_name='crawlhistory',
            name='mapped_total',
            field=models.IntegerField(default=0, verbose_name='Mapped Total'),
        ),
        migrations.AddField(
            model_name='crawlhistory',
            name='scimago_total',
            field=models.IntegerField(default=0, verbose_name='SCImago Total'),
        ),
    ]
