# Generated by Django 6.0.3 on 2026-07-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0008_crawlhistory_bioxbio_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='publication',
            name='eprint_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Eprint PDF URL'),
        ),
        migrations.AddField(
            model_name='publication',
            name='issue',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Issue'),
        ),
        migrations.AddField(
            model_name='publication',
            name='pages',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Pages'),
        ),
        migrations.AddField(
            model_name='publication',
            name='pub_date',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Publication Date'),
        ),
        migrations.AddField(
            model_name='publication',
            name='pub_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Publication URL'),
        ),
        migrations.AddField(
            model_name='publication',
            name='publisher',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Publisher'),
        ),
        migrations.AddField(
            model_name='publication',
            name='volume',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Volume'),
        ),
    ]
