# Generated by Django 6.0.3 on 2026-07-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0009_publication_description_publication_eprint_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='url_all_versions',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='All Versions URL'),
        ),
        migrations.AddField(
            model_name='publication',
            name='url_related_articles',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Related Articles URL'),
        ),
        migrations.AddField(
            model_name='publication',
            name='versions_count',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Versions Count'),
        ),
    ]
