# Generated by Django 6.0.3 on 2026-07-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0010_publication_url_all_versions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='email_domain',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Email Domain'),
        ),
    ]
