# Generated by Django 6.0.3 on 2026-07-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0011_authorprofile_email_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='cites_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Scholar Cites ID'),
        ),
        migrations.AddField(
            model_name='publication',
            name='url_scholar_article',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Scholar Article Link'),
        ),
    ]
