# Generated by Django 6.0.3 on 2026-07-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0012_publication_cites_id_publication_url_scholar_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoScanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('scan_interval_hours', models.IntegerField(default=24, verbose_name='Scan Interval Hours')),
                ('batch_size_per_hour', models.IntegerField(default=8, verbose_name='Batch Size Per Hour')),
                ('delay_min_seconds', models.IntegerField(default=8, verbose_name='Delay Min Seconds')),
                ('delay_max_seconds', models.IntegerField(default=15, verbose_name='Delay Max Seconds')),
                ('cooldown_min_seconds', models.IntegerField(default=45, verbose_name='Cooldown Min Seconds')),
                ('cooldown_max_seconds', models.IntegerField(default=90, verbose_name='Cooldown Max Seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auto Scan Config',
                'verbose_name_plural': 'Auto Scan Configs',
                'db_table': 'scholar_auto_scan_config',
            },
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='auto_scan_enabled',
            field=models.BooleanField(default=True, verbose_name='Auto Scan Enabled'),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='last_scan_status',
            field=models.CharField(default='PENDING', max_length=50, verbose_name='Last Scan Status'),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='last_scraped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Scraped At'),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='publication_count_cached',
            field=models.IntegerField(default=0, verbose_name='Publication Count Cached'),
        ),
    ]
