# Generated by Django 6.0.3 on 2026-07-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0013_autoscanconfig_authorprofile_auto_scan_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoscanconfig',
            name='current_job_detail',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Current Job Detail'),
        ),
        migrations.AddField(
            model_name='autoscanconfig',
            name='current_job_progress',
            field=models.IntegerField(default=0, verbose_name='Current Job Progress'),
        ),
        migrations.AddField(
            model_name='autoscanconfig',
            name='current_job_status',
            field=models.CharField(default='IDLE', max_length=50, verbose_name='Current Job Status'),
        ),
        migrations.AddField(
            model_name='autoscanconfig',
            name='frequency_type',
            field=models.CharField(default='WEEKLY', max_length=20, verbose_name='Frequency Type'),
        ),
        migrations.AddField(
            model_name='autoscanconfig',
            name='preferred_day_of_month',
            field=models.IntegerField(default=1, verbose_name='Preferred Day of Month'),
        ),
        migrations.AddField(
            model_name='autoscanconfig',
            name='preferred_hour',
            field=models.IntegerField(default=2, verbose_name='Preferred Hour'),
        ),
        migrations.AddField(
            model_name='autoscanconfig',
            name='preferred_minute',
            field=models.IntegerField(default=0, verbose_name='Preferred Minute'),
        ),
        migrations.AddField(
            model_name='autoscanconfig',
            name='preferred_weekday',
            field=models.IntegerField(default=0, verbose_name='Preferred Weekday'),
        ),
        migrations.AlterField(
            model_name='autoscanconfig',
            name='scan_interval_hours',
            field=models.IntegerField(default=168, verbose_name='Scan Interval Hours'),
        ),
    ]
