# Generated by Django 6.0.3 on 2026-07-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0014_autoscanconfig_current_job_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntiBlockConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_tor_proxy', models.BooleanField(default=True)),
                ('use_free_proxy_pool', models.BooleanField(default=True)),
                ('custom_proxy_list', models.TextField(blank=True, default='')),
                ('enable_captcha_solver', models.BooleanField(default=False)),
                ('captcha_provider', models.CharField(default='2captcha', max_length=50)),
                ('captcha_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('max_retries_per_request', models.IntegerField(default=5)),
                ('adaptive_backoff_enabled', models.BooleanField(default=True)),
                ('base_delay_seconds', models.FloatField(default=1.0)),
                ('max_delay_seconds', models.FloatField(default=15.0)),
                ('total_requests_count', models.IntegerField(default=0)),
                ('captcha_encountered_count', models.IntegerField(default=0)),
                ('captcha_solved_count', models.IntegerField(default=0)),
                ('ip_rotations_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Anti-Block Config',
            },
        ),
    ]
