# Generated by Django 6.0.3 on 2026-07-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0015_antiblockconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antiblockconfig',
            options={'verbose_name': 'Anti-Block Config', 'verbose_name_plural': 'Anti-Block Configs'},
        ),
        migrations.AlterField(
            model_name='antiblockconfig',
            name='adaptive_backoff_enabled',
            field=models.BooleanField(default=True, verbose_name='Adaptive Backoff Enabled'),
        ),
        migrations.AlterField(
            model_name='antiblockconfig',
            name='base_delay_seconds',
            field=models.FloatField(default=1.0, verbose_name='Base Delay Seconds'),
        ),
        migrations.AlterField(
            model_name='antiblockconfig',
            name='captcha_api_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='CAPTCHA API Key'),
        ),
        migrations.AlterField(
            model_name='antiblockconfig',
            name='captcha_encountered_count',
            field=models.IntegerField(default=0, verbose_name='CAPTCHA Encountered Count'),
        ),
        migrations.AlterField(
            model_name='antiblockconfig',
            name='captcha_provider',
            field=models.CharField(default='2captcha', max_length=50, verbose_name='CAPTCHA Provider'),
        ),
        migrations.AlterField(
            model_name='antiblockconfig',
            name='captcha_solved_count',
            field=models.IntegerField(default=0, verbose_name='CAPTCHA Solved Count'),
        ),
        migrations.AlterField(
            model_name='antiblockconfig',
            name='custom_proxy_list',
            field=models.TextField(blank=True, default='', verbose_name='Custom Proxy List'),
        ),
        migrations.AlterField(
            model_name='antiblockconfig',
            name='enable_captcha_solver',
            field=models.BooleanField(default=False, verbose_name='Enable CAPTCHA Solver'),
        ),
        migrations.AlterField(
            model_name='antiblockconfig',
            name='ip_rotations_count',
            field=models.IntegerField(default=0, verbose_name='IP Rotations Count'),
        ),
        migrations.AlterField(
            model_name='antiblockconfig',
            name='max_delay_seconds',
            field=models.FloatField(default=15.0, verbose_name='Max Delay Seconds'),
        ),
        migrations.AlterField(
            model_name='antiblockconfig',
            name='max_retries_per_request',
            field=models.IntegerField(default=5, verbose_name='Max Retries Per Request'),
        ),
        migrations.AlterField(
            model_name='antiblockconfig',
            name='total_requests_count',
            field=models.IntegerField(default=0, verbose_name='Total Requests Count'),
        ),
        migrations.AlterField(
            model_name='antiblockconfig',
            name='use_free_proxy_pool',
            field=models.BooleanField(default=True, verbose_name='Use Free Proxy Pool'),
        ),
        migrations.AlterField(
            model_name='antiblockconfig',
            name='use_tor_proxy',
            field=models.BooleanField(default=True, verbose_name='Use Tor Proxy'),
        ),
        migrations.AlterModelTable(
            name='antiblockconfig',
            table='scholar_anti_block_config',
        ),
    ]
