# Generated by Django 6.0.3 on 2026-07-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0016_alter_antiblockconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='citedby5y',
            field=models.IntegerField(default=0, help_text='Trích dẫn 5 năm gần nhất', verbose_name='5-Year Citations'),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='cites_per_year',
            field=models.JSONField(blank=True, default=dict, help_text='Lịch sử trích dẫn theo từng năm của Tác giả', verbose_name='Citations Per Year History'),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='hindex5y',
            field=models.IntegerField(default=0, help_text='h-index 5 năm gần nhất', verbose_name='5-Year H-Index'),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='i10index5y',
            field=models.IntegerField(default=0, help_text='i10-index 5 năm gần nhất', verbose_name='5-Year i10-Index'),
        ),
    ]
