# Generated by Django 6.0.3 on 2026-07-22 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0017_authorprofile_citedby5y_authorprofile_cites_per_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scholar_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Scholar URL')),
                ('scholar_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Scholar ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Chưa gửi hồ sơ'), ('PENDING', 'Đang chờ duyệt'), ('APPROVED', 'Đã phê duyệt'), ('REJECTED', 'Từ chối')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('total_citations', models.IntegerField(default=0, verbose_name='Total Citations')),
                ('h_index', models.IntegerField(default=0, verbose_name='H-Index')),
                ('i10_index', models.IntegerField(default=0, verbose_name='i10-Index')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scholar_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'scholar_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScholarPublication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500, verbose_name='Publication Title')),
                ('authors', models.TextField(blank=True, default='', verbose_name='Authors')),
                ('journal', models.CharField(blank=True, default='', max_length=500, verbose_name='Journal / Conference')),
                ('pub_year', models.IntegerField(blank=True, null=True, verbose_name='Publication Year')),
                ('citations', models.IntegerField(default=0, verbose_name='Citations Count')),
                ('url', models.URLField(blank=True, default='', max_length=500, verbose_name='Publication Link')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='scholar.scholarprofile', verbose_name='Scholar Profile')),
            ],
            options={
                'db_table': 'scholar_user_publications',
                'ordering': ['-pub_year', '-citations'],
            },
        ),
    ]
