# Generated by Django 6.0.3 on 2026-07-22 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0018_scholarprofile_scholarpublication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarprofile',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Scholar Profile',
                'verbose_name_plural': 'Scholar Profiles',
            },
        ),
        migrations.AlterModelOptions(
            name='scholarpublication',
            options={
                'ordering': ['-pub_year', '-citations'],
                'verbose_name': 'Scholar Publication',
                'verbose_name_plural': 'Scholar Publications',
            },
        ),
    ]

