# Generated by Django 6.0.3 on 2026-07-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0019_alter_scholarprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarprofile',
            name='academic_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Academic Title'),
        ),
        migrations.AddField(
            model_name='scholarprofile',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='scholarprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='scholarprofile',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='scholarprofile',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Position'),
        ),
    ]
