# Generated by Django 6.0.3 on 2026-07-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0020_scholarprofile_academic_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoscanconfig',
            name='default_from_email',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Default From Email'),
        ),
        migrations.AddField(
            model_name='autoscanconfig',
            name='email_host',
            field=models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='Email Host'),
        ),
        migrations.AddField(
            model_name='autoscanconfig',
            name='email_host_password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Email Host Password'),
        ),
        migrations.AddField(
            model_name='autoscanconfig',
            name='email_host_user',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Email Host User'),
        ),
        migrations.AddField(
            model_name='autoscanconfig',
            name='email_port',
            field=models.IntegerField(default=587, verbose_name='Email Port'),
        ),
        migrations.AddField(
            model_name='autoscanconfig',
            name='email_use_tls',
            field=models.BooleanField(default=True, verbose_name='Email Use TLS'),
        ),
    ]
