# Generated by Django 6.0.3 on 2026-07-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0021_autoscanconfig_default_from_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(max_length=100, unique=True, verbose_name='Template Key')),
                ('name', models.CharField(max_length=255, verbose_name='Template Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject Line')),
                ('html_content', models.TextField(verbose_name='HTML Content')),
                ('available_variables', models.JSONField(blank=True, default=list, verbose_name='Available Variables')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'db_table': 'scholar_email_template',
            },
        ),
    ]
