# Generated by Django 6.0.3 on 2026-07-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0022_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarprofile',
            name='request_type',
            field=models.CharField(choices=[('NEW', 'Hồ sơ mới'), ('UPDATE', 'Yêu cầu cập nhật')], db_index=True, default='NEW', max_length=20, verbose_name='Request Type'),
        ),
    ]
